-- Identity and gardens baseline: application profiles, Firebase identity
-- links, account state, gardens, garden membership, an invitation skeleton,
-- consent records, and the cross-cutting platform tables every module's write
-- path depends on (idempotency, transactional outbox, synchronization change
-- log, audit log).
--
-- No coordinate spaces, map objects, or geometry revisions are created here:
-- the garden row is identity and lifecycle metadata only. Garden mapping
-- content arrives with P3-DATA-01.
--
-- Source: implementation-plan.md work package P2-DATA-01;
--         architecture/identity-and-authorization.md;
--         architecture/data-and-geospatial-design.md, sections
--         "3. Schema Ownership", "4. Identifier Strategy", "5. Time and Actors",
--         "13. Revision Model", "17. Idempotency Records", "18. Transactional
--         Outbox", "16. Synchronization Change Log".

-- Up Migration

-- Every table below is created while acting as verdery_migration, not as
-- whichever identity is running the migration, so the default privileges
-- 1784710800000_platform-baseline.sql already granted on these schemas take
-- effect automatically and verdery_application receives row access without a
-- second, easy-to-forget GRANT per table. Confirmed by the "grants the
-- application role row access to tables the migration role creates" test in
-- tests/migrations/platform-baseline.test.ts.
SET ROLE verdery_migration;

-- Identifiers are UUIDv7 generated by the client or a trusted server
-- component before the row is written, never a database default, so an
-- offline client can create a record without waiting for server allocation.
-- Source: data-and-geospatial-design.md, section "4. Identifier Strategy".

CREATE TABLE identity_access.profile (
  id uuid PRIMARY KEY,
  firebase_uid text NOT NULL,
  account_state text NOT NULL DEFAULT 'pending',
  locale text NOT NULL DEFAULT 'en',
  time_zone text NOT NULL DEFAULT 'UTC',
  revision bigint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT profile_firebase_uid_key UNIQUE (firebase_uid),
  -- Source: architecture/identity-and-authorization.md, section "7. Account States".
  CONSTRAINT profile_account_state_check CHECK (
    account_state IN ('pending', 'active', 'suspended', 'deletion_requested', 'disabled', 'purged')
  )
);

-- Firebase owns provider links as the authentication authority; this table is
-- a narrower, application-owned shadow of the verified identifiers Grow
-- Garden itself needs for support lookups and duplicate-profile prevention,
-- not a replacement for Firebase's own record.
--
-- `provider` deliberately has no CHECK enumerating exact values. Firebase's
-- own sign-in-provider identifiers (for example whether email link and
-- password sign-in share one provider string) are an implementation detail of
-- the Firebase Admin SDK response, not a fact this migration should assert
-- and risk getting wrong in a way only a later migration could fix. The
-- identity-access module validates and normalizes provider identifiers in
-- code, where a mistake costs a code change, not a migration.
--
-- Source: architecture/identity-and-authorization.md, sections "2. Identity
-- Authority", "3. Initial Sign-In Methods", "6. Application Profile
-- Provisioning".
CREATE TABLE identity_access.identity_provider_link (
  id uuid PRIMARY KEY,
  profile_id uuid NOT NULL REFERENCES identity_access.profile (id),
  provider text NOT NULL,
  provider_uid text NOT NULL,
  verified_email text,
  linked_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT identity_provider_link_profile_provider_key UNIQUE (profile_id, provider),
  CONSTRAINT identity_provider_link_provider_uid_key UNIQUE (provider, provider_uid)
);

-- One row per granted consent, not a single column on `profile`, so a new
-- consent type (privacy policy, marketing) never requires widening the
-- profile row and history of what was granted when is preserved.
--
-- `consent_type` has no CHECK for the same reason as `identity_provider_link.
-- provider` above: the initial set of consent types is a product decision the
-- identity-access module encodes, not a fact this schema should freeze.
CREATE TABLE identity_access.consent_record (
  id uuid PRIMARY KEY,
  profile_id uuid NOT NULL REFERENCES identity_access.profile (id),
  consent_type text NOT NULL,
  consent_version text NOT NULL,
  granted_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX identity_provider_link_profile_id_idx
  ON identity_access.identity_provider_link (profile_id);
CREATE INDEX consent_record_profile_id_idx ON identity_access.consent_record (profile_id);

-- The garden aggregate is identity and lifecycle metadata only. Ownership is
-- expressed through `collaboration.membership` (a role, not a foreign key on
-- this table), matching "the permission matrix is implemented as stable
-- capabilities rather than scattered role-name comparisons."
--
-- Source: architecture/identity-and-authorization.md, section "8. Garden
-- Roles"; architecture/data-and-geospatial-design.md, section "6. Garden
-- Aggregate".
CREATE TABLE gardens_mapping.garden (
  id uuid PRIMARY KEY,
  name text NOT NULL,
  lifecycle_state text NOT NULL DEFAULT 'active',
  revision bigint NOT NULL DEFAULT 1,
  created_by_profile_id uuid NOT NULL REFERENCES identity_access.profile (id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deletion_requested_at timestamptz,
  CONSTRAINT garden_name_not_blank CHECK (btrim(name) <> ''),
  CONSTRAINT garden_name_length CHECK (char_length(name) <= 120),
  -- 'deleted' is deliberately absent: no purge workflow exists yet to reach
  -- it, and adding a state nothing can transition into would be untested
  -- dead code. It arrives with the purge work package that can exercise it.
  CONSTRAINT garden_lifecycle_state_check CHECK (
    lifecycle_state IN ('active', 'archived', 'deletion_requested')
  )
);

CREATE INDEX garden_lifecycle_state_idx ON gardens_mapping.garden (lifecycle_state);
CREATE INDEX garden_created_by_profile_id_idx ON gardens_mapping.garden (created_by_profile_id);

-- Source: architecture/identity-and-authorization.md, section "8. Garden Roles".
CREATE TABLE collaboration.membership (
  id uuid PRIMARY KEY,
  garden_id uuid NOT NULL REFERENCES gardens_mapping.garden (id),
  profile_id uuid NOT NULL REFERENCES identity_access.profile (id),
  role text NOT NULL,
  state text NOT NULL DEFAULT 'active',
  revision bigint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT membership_garden_profile_key UNIQUE (garden_id, profile_id),
  CONSTRAINT membership_role_check CHECK (role IN ('owner', 'editor', 'viewer')),
  CONSTRAINT membership_state_check CHECK (state IN ('active', 'removed'))
);

-- Listing "gardens this profile can access" filters by profile_id first; the
-- unique constraint above leads with garden_id and cannot serve that query.
CREATE INDEX membership_profile_id_idx ON collaboration.membership (profile_id, state);

-- Skeleton only: no invitation endpoint exists yet (out of scope for
-- P2-API-01). The table exists now so P2-DATA-01's ownership and constraint
-- tests can cover its shape before any application code writes to it.
--
-- Tokens are stored only as hashes, never the opaque token itself.
-- Source: architecture/identity-and-authorization.md, section "10. Invitations".
CREATE TABLE collaboration.invitation (
  id uuid PRIMARY KEY,
  garden_id uuid NOT NULL REFERENCES gardens_mapping.garden (id),
  inviter_profile_id uuid NOT NULL REFERENCES identity_access.profile (id),
  intended_role text NOT NULL,
  intended_email text,
  token_hash text NOT NULL,
  state text NOT NULL DEFAULT 'pending',
  accepted_by_profile_id uuid REFERENCES identity_access.profile (id),
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  CONSTRAINT invitation_token_hash_key UNIQUE (token_hash),
  -- Ownership moves only through the dedicated transfer flow (section "11.
  -- Ownership Transfer"), never through an accepted invitation.
  CONSTRAINT invitation_intended_role_check CHECK (intended_role IN ('editor', 'viewer')),
  CONSTRAINT invitation_state_check CHECK (state IN ('pending', 'accepted', 'revoked', 'expired'))
);

CREATE INDEX invitation_garden_id_idx ON collaboration.invitation (garden_id);
CREATE INDEX invitation_inviter_profile_id_idx ON collaboration.invitation (inviter_profile_id);

-- Keyed by actor scope, operation, and the client-supplied Idempotency-Key so
-- a retried request with the same key and the same command replays the same
-- accepted result. Reusing a key with a different request_fingerprint is an
-- application-level conflict, not something this table enforces itself.
--
-- Written exactly once, already carrying its final response, in the same
-- transaction as the command's own domain writes, right before that
-- transaction commits — never as a separate "processing" row created before
-- the result is known. A speculative "processing" row would need to be read
-- back inside the same transaction on conflict, which cannot work: Postgres
-- aborts an entire transaction on the first statement error, so a caught
-- unique-violation still leaves every later statement in that same
-- transaction failing with "current transaction is aborted." The command
-- handler instead lets a conflicting insert abort and roll back the whole
-- transaction, then re-reads the now-committed row in a fresh one to decide
-- replay versus a genuine key-reused conflict.
--
-- Source: architecture/backend-modular-monolith.md, section "15. Idempotency";
--         architecture/data-and-geospatial-design.md, section
--         "17. Idempotency Records".
CREATE TABLE platform.idempotency_record (
  actor_profile_id uuid NOT NULL REFERENCES identity_access.profile (id) ON DELETE CASCADE,
  operation text NOT NULL,
  idempotency_key text NOT NULL,
  request_fingerprint text NOT NULL,
  response_status_code integer NOT NULL,
  response_body jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  PRIMARY KEY (actor_profile_id, operation, idempotency_key)
);

-- Supports a future cleanup job; no such job exists yet in Phase 2.
CREATE INDEX idempotency_record_expires_at_idx ON platform.idempotency_record (expires_at);

-- Aggregate reference is deliberately polymorphic (aggregate_type plus a
-- plain uuid) with no foreign key: an event must remain readable after its
-- aggregate is purged, which a hard reference would prevent.
--
-- Source: architecture/data-and-geospatial-design.md, section
-- "18. Transactional Outbox".
CREATE TABLE platform.outbox_event (
  id uuid PRIMARY KEY,
  event_type text NOT NULL,
  event_version integer NOT NULL DEFAULT 1,
  aggregate_type text NOT NULL,
  aggregate_id uuid NOT NULL,
  payload jsonb NOT NULL,
  trace_id text,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz,
  publish_attempts integer NOT NULL DEFAULT 0
);

-- A relay that publishes to Pub/Sub is not part of Phase 2; this index is
-- what that relay will scan once it exists.
CREATE INDEX outbox_event_unpublished_idx ON platform.outbox_event (occurred_at)
  WHERE published_at IS NULL;

-- Skeleton only: no endpoint reads or writes this table in Phase 2. The
-- generic native sync protocol (POST /v1/sync/push, GET /v1/sync/changes) is
-- not part of P2-API-01, which is limited to ordinary garden CRUD; P2-IOS-01's
-- "local read model" is populated by calling that CRUD API directly. This
-- table exists now so its ownership and shape are covered by migration tests
-- ahead of the module that will populate it.
--
-- No foreign keys to garden or profile: a deletion tombstone must remain
-- readable after the record it describes no longer exists.
--
-- Source: architecture/data-and-geospatial-design.md, section
-- "16. Synchronization Change Log"; architecture/offline-synchronization.md.
CREATE TABLE platform.sync_change (
  sequence bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  garden_id uuid,
  record_id uuid NOT NULL,
  record_type text NOT NULL,
  operation text NOT NULL,
  record_revision bigint NOT NULL,
  committed_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sync_change_operation_check CHECK (operation IN ('upsert', 'delete'))
);

CREATE INDEX sync_change_garden_sequence_idx ON platform.sync_change (garden_id, sequence);

-- One generic append-only log for every audited event category listed in
-- architecture/identity-and-authorization.md section "17. Security Logging"
-- (provider link/unlink, session revocation, role and membership changes,
-- invitation lifecycle, ownership transfer, support access, account
-- suspension and deletion) plus garden lifecycle changes, rather than a
-- separate table per concern. `subject_id` has no foreign key for the same
-- reason as `outbox_event.aggregate_id`: an audit record must survive its
-- subject's deletion.
CREATE TABLE platform.audit_event (
  id uuid PRIMARY KEY,
  event_type text NOT NULL,
  subject_type text NOT NULL,
  subject_id uuid NOT NULL,
  actor_profile_id uuid REFERENCES identity_access.profile (id),
  actor_type text NOT NULL DEFAULT 'user',
  details jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT audit_event_actor_type_check CHECK (actor_type IN ('user', 'system', 'administrator'))
);

CREATE INDEX audit_event_subject_idx ON platform.audit_event (subject_type, subject_id, occurred_at DESC);

RESET ROLE;

-- Down Migration

SET ROLE verdery_migration;

DROP TABLE IF EXISTS platform.audit_event CASCADE;
DROP TABLE IF EXISTS platform.sync_change CASCADE;
DROP TABLE IF EXISTS platform.outbox_event CASCADE;
DROP TABLE IF EXISTS platform.idempotency_record CASCADE;
DROP TABLE IF EXISTS collaboration.invitation CASCADE;
DROP TABLE IF EXISTS collaboration.membership CASCADE;
DROP TABLE IF EXISTS gardens_mapping.garden CASCADE;
DROP TABLE IF EXISTS identity_access.consent_record CASCADE;
DROP TABLE IF EXISTS identity_access.identity_provider_link CASCADE;
DROP TABLE IF EXISTS identity_access.profile CASCADE;

RESET ROLE;
