/**
 * Request correlation.
 *
 * Every request carries a `requestId` generated by the server and a
 * `correlationId` that a client may supply to tie several requests of one
 * user-visible workflow together. Both appear in logs and the correlation
 * identifier is returned to the client so a support report can be traced.
 *
 * Source: architecture/observability-and-analytics.md, section "4. Correlation".
 */

import { randomUUID } from 'node:crypto';
import type { FastifyInstance } from 'fastify';

export const CORRELATION_ID_HEADER = 'x-correlation-id';

/**
 * Client-supplied identifiers are untrusted input that ends up in log records,
 * so only a conservative token shape is accepted; anything else is replaced
 * rather than rejected, because a malformed header must not fail a request.
 */
const ACCEPTED_CORRELATION_ID = /^[A-Za-z0-9._-]{1,128}$/;

/** Returns the client-supplied correlation identifier, or the fallback. */
export function resolveCorrelationId(
  supplied: string | string[] | undefined,
  fallback: string,
): string {
  // A repeated header arrives as an array; only the first value is considered.
  const candidate = Array.isArray(supplied) ? supplied[0] : supplied;

  if (candidate !== undefined && ACCEPTED_CORRELATION_ID.test(candidate)) {
    return candidate;
  }

  return fallback;
}

/** Generates the per-request identifier used when no correlation ID is supplied. */
export function generateRequestId(): string {
  return randomUUID();
}

declare module 'fastify' {
  interface FastifyRequest {
    correlationId: string;
  }
}

/**
 * Registers correlation handling on the instance.
 *
 * Runs in `onRequest` so that the identifier exists before authentication,
 * validation, or any handler can fail.
 */
export function registerCorrelation(app: FastifyInstance): void {
  app.decorateRequest('correlationId', '');

  app.addHook('onRequest', (request, reply, done) => {
    const correlationId = resolveCorrelationId(request.headers[CORRELATION_ID_HEADER], request.id);

    request.correlationId = correlationId;
    // Every subsequent log line for this request carries the identifier, so a
    // support report quoting it finds the whole request without a text search.
    request.log = request.log.child({ correlationId });
    void reply.header(CORRELATION_ID_HEADER, correlationId);
    done();
  });
}
