import { expect, test, type Page } from '@playwright/test';

import { fetchEmailSignInLink, freshTestEmail } from './support/auth-emulator';
import { copy } from './support/copy';
import { fetchPlantId, seedCareLoopCandidates } from './support/recommendation-seed';

/**
 * The web complete care-loop E2E — P7-WEB-01's acceptance evidence.
 *
 * One user, one garden, one plant, and four seeded recommendation
 * candidates (one per launch rule — see `support/recommendation-seed.ts`
 * for why candidates are seeded by SQL rather than generated by the
 * engine's OIDC-guarded sweep). Everything after generation is the real
 * stack end to end: the Today GET marks first presentation and re-derives
 * the priority order from the stored factors, and every control drives its
 * real command — complete, postpone (with a horizon), mark-irrelevant,
 * dismiss, and conversion into a task that then appears on the tasks page
 * carrying its recommendation origin.
 *
 * Action titles resolve from the running build's own rule catalog, so the
 * literals below are the catalog's `actionTitle` values — a catalog change
 * fails here loudly, exactly like a copy change breaks `copy.ts` selectors.
 *
 * Source: docs/implementation-plan.md, work package P7-WEB-01
 * ("Web complete care-loop E2E").
 */

const FROST_TITLE = 'Consider protective cover against forecast frost';
const HARVEST_TITLE = 'Check ripeness and harvest what is ready';
const OBSERVATION_TITLE = 'Record a quick condition check for this plant';
const WATERING_TITLE = 'Check whether this plant needs watering';

function card(page: Page, actionTitle: string) {
  return page.getByRole('listitem').filter({ hasText: actionTitle });
}

test.describe.serial('care loop: Today set, feedback controls, and task conversion', () => {
  const email = freshTestEmail('care-loop');
  const gardenName = `E2E Care Loop ${Date.now().toString()}`;
  const plantName = 'E2E Tomato row';
  let gardenId = '';

  /**
   * Playwright's per-test context isolation drops the session between
   * tests, so each test signs in again through the real magic-link flow —
   * the same posture `register-and-create-garden.spec.ts` takes. The
   * emulator's `findLast` polling always resolves the newest link for this
   * address.
   */
  async function signIn(page: Page): Promise<void> {
    await page.goto('/auth/sign-in');
    await page.getByLabel(copy.emailLabel).fill(email);
    await page.getByRole('button', { name: copy.emailSubmit }).click();
    await expect(page.getByText(copy.emailLinkSent)).toBeVisible();
    await page.goto(await fetchEmailSignInLink(email));
    await expect(page).toHaveURL(/\/application\/gardens$/);
  }

  test('sign in, create the garden and plant, and seed the four candidates', async ({ page }) => {
    await signIn(page);
    await page.getByLabel(copy.gardensCreateNameLabel).fill(gardenName);
    await page.getByRole('button', { name: copy.gardensCreateSubmit }).click();
    await expect(page).toHaveURL(/\/application\/gardens\/[^/]+$/);
    gardenId = page.url().split('/').pop() ?? '';
    expect(gardenId).not.toBe('');

    await page.goto(`/application/gardens/${gardenId}/plants`);
    await page.getByLabel(copy.plantDisplayNameLabel).fill(plantName);
    await page.getByRole('button', { name: copy.plantAddSubmit }).click();
    await expect(page).toHaveURL(/\/plants\/[^/]+$/);

    await seedCareLoopCandidates(gardenId, await fetchPlantId(gardenId));
  });

  test('Today presents the prioritized set with reason, urgency, uncertainty, and evidence', async ({
    page,
  }) => {
    await signIn(page);
    await page.goto(`/application/gardens/${gardenId}`);
    await page.getByRole('link', { name: copy.todayNavLink }).click();
    await expect(page).toHaveURL(/\/today$/);

    // Priority order re-derived server-side from the seeded factors:
    // frost (75) > harvest (65) > observation (40) > watering (25).
    await expect(page.getByRole('listitem')).toHaveCount(4);
    await expect(page.getByRole('listitem').first()).toContainText(FROST_TITLE);

    // The elevated-risk frost item carries its caution, with its reason
    // visible. The caution NOTE is asserted rather than the pill label:
    // Playwright's substring matching would find "elevated risk" in both.
    const frost = card(page, FROST_TITLE);
    await expect(frost.getByText(copy.todayElevatedRiskNote)).toBeVisible();
    await expect(frost.getByText(/forecast expects a low of -2 C/)).toBeVisible();

    // Uncertainty is honest: the stale-weather confidence basis is labeled.
    const watering = card(page, WATERING_TITLE);
    await expect(watering.getByText(new RegExp(copy.todayStaleWeatherBasis))).toBeVisible();

    // Evidence expands to readable entries, resolving the carried plant name.
    await watering.getByRole('button', { name: copy.todayDetailsShow }).click();
    await expect(watering.getByText('Rule watering.dry-spell-check v1')).toBeVisible();
    await expect(watering.getByText(`Plant: ${plantName}`)).toBeVisible();
    await expect(watering.getByText('daysSinceRain: 9')).toBeVisible();
  });

  test('complete, postpone, and dismiss each remove their item through the real commands', async ({
    page,
  }) => {
    await signIn(page);
    await page.goto(`/application/gardens/${gardenId}/today`);
    await expect(page.getByRole('listitem')).toHaveCount(4);

    // Complete the harvest check.
    await card(page, HARVEST_TITLE).getByRole('button', { name: copy.todayComplete }).click();
    await expect(card(page, HARVEST_TITLE)).toHaveCount(0);

    // Postpone the observation reminder with an explicit horizon.
    const observation = card(page, OBSERVATION_TITLE);
    await observation.getByRole('button', { name: copy.todayPostpone }).click();
    await observation.getByLabel(copy.todayPostponeUntilLabel).fill('2027-01-01T09:00');
    await observation.getByRole('button', { name: copy.todayPostpone }).last().click();
    await expect(card(page, OBSERVATION_TITLE)).toHaveCount(0);

    // Mark the watering check irrelevant (item stays), then dismiss it.
    const watering = card(page, WATERING_TITLE);
    await watering.getByRole('button', { name: copy.todayMarkIrrelevant }).click();
    await expect(watering.getByText(copy.todayMarkIrrelevantRecorded)).toBeVisible();
    await watering.getByRole('button', { name: copy.todayDismiss }).click();
    await expect(card(page, WATERING_TITLE)).toHaveCount(0);

    await expect(page.getByRole('listitem')).toHaveCount(1);
  });

  test('converting the last item creates the linked task and empties Today', async ({ page }) => {
    await signIn(page);
    await page.goto(`/application/gardens/${gardenId}/today`);
    await expect(page.getByRole('listitem')).toHaveCount(1);

    await card(page, FROST_TITLE).getByRole('button', { name: copy.todayConvertToTask }).click();

    // A successful conversion navigates to the tasks page, where the
    // suggested task now lives with its recommendation origin visible.
    await expect(page).toHaveURL(/\/tasks$/);
    const task = page.getByRole('listitem').filter({ hasText: FROST_TITLE });
    await expect(task).toHaveCount(1);
    await expect(task.getByText(copy.taskStatusPlanned)).toBeVisible();
    await expect(task.getByText(copy.taskFromRecommendation)).toBeVisible();
    // The stored explanation survives onto the task as its notes.
    await expect(task.getByText(/forecast expects a low of -2 C/)).toBeVisible();

    await page.goto(`/application/gardens/${gardenId}/today`);
    await expect(page.getByText(copy.todayEmpty)).toBeVisible();
  });
});
