/**
 * UUIDv7 identifiers, generated by trusted server components.
 *
 * Time-ordered for index locality, but never treated as an authoritative
 * creation timestamp — `created_at` columns are.
 *
 * Source: architecture/data-and-geospatial-design.md, section
 * "4. Identifier Strategy".
 */

import { v7 } from 'uuid';

export type Uuid = string;

export function generateUuidV7(): Uuid {
  return v7();
}
