import CoreDomain
import CoreNetworking
import Foundation

/// Use cases for the plant inventory operations this pass gives a UI to.
///
/// `AddPlant`, `UpdatePlantDetails`, `TransitionPlantLifecycleStage`,
/// `SetPlantStatus`, and `MovePlant` route through the same atomic
/// local-projection-plus-outbox pattern `FeatureGardens`'s four commands
/// (P5-IOS-02, Stage 4a) and `FeatureMap`'s commands (Stage 4b) already
/// established, as of P5-IOS-02 Stage 4c: no network call, one GRDB
/// transaction via `LocalPlantStore.commitOfflineMutation`. `GetPlant` and
/// `SearchTaxonomyReferences` stay online, gateway-backed reads — a plant
/// detail screen opened while online still fetches fresh from the network
/// for display, the same way `FeatureGardens`'s `ListGardens`/`GetGarden`
/// still call `GardenGateway` directly for reads even after Stage 4a.
///
/// `AddPlantFromPhoto`, `AttachPlantPhoto`, `SetPrimaryPlantPhoto`, and
/// `ConfirmPlantIdentification` have no use case here, even though
/// `PlantGateway` implements and tests all four: every one of them needs a
/// `mediaId` or an `identificationId` this client has no way to produce yet
/// (see `PlantsHomeView`'s doc comment, and
/// `docs/development/deferred-capabilities.md`'s "Photo and file attachment"
/// entry, which lists `ConfirmPlantIdentification` alongside the three
/// photo-dependent commands for exactly this reason: an `identificationId`
/// only ever comes from a prior `plant_identification` suggestion, which only
/// `AddPlantFromPhoto`/photo-based identification produces — there is no
/// separate, non-photo path to one). Confirmed unreachable from any real UI
/// flow today by grep, not assumed — see this stage's own report. This
/// remains true after Stage 4c: none of the four gained a use case, so none
/// of the four gained offline support either, matching Stage 4b's identical
/// treatment of `upsertCalibration`/`decideProposal`.
///
/// Source: implementation-plan.md work package P4-IOS-01, P5-IOS-02;
/// packages/api-contracts/openapi.yaml, tag `Plants`, `Synchronization`.
public struct AddPlant: Sendable {
    private let localStore: any LocalPlantStore
    private let profileId: String
    private let now: @Sendable () -> Date
    private let generateOperationId: @Sendable () -> String
    private let generatePlantId: @Sendable () -> String

    public init(
        localStore: any LocalPlantStore,
        profileId: String,
        now: @escaping @Sendable () -> Date = Date.init,
        generateOperationId: @escaping @Sendable () -> String = UUIDv7.generate,
        generatePlantId: @escaping @Sendable () -> String = UUIDv7.generate
    ) {
        self.localStore = localStore
        self.profileId = profileId
        self.now = now
        self.generateOperationId = generateOperationId
        self.generatePlantId = generatePlantId
    }

    public func callAsFunction(
        gardenId: String,
        displayName: String,
        taxonomyReferenceId: String? = nil,
        varietyLabel: String? = nil,
        acquisitionDate: String? = nil,
        acquisitionDateType: PlantAcquisitionDateType? = nil,
        groupingKind: PlantGroupingKind,
        quantity: Int? = nil,
        gardenAreaMapObjectId: String? = nil,
        placementMapObjectId: String? = nil
    ) async throws -> Plant {
        let trimmedName = try validatedDisplayName(displayName)
        let plantId = generatePlantId()
        let timestamp = now()
        let operationId = generateOperationId()

        return try await localStore.commitOfflineMutation(plantId: plantId) { current in
            // `current` is always `nil` here: `plantId` was just generated by
            // `generatePlantId()` above and cannot already have a local row.
            let projection = Plant(
                id: plantId,
                gardenId: gardenId,
                gardenAreaMapObjectId: gardenAreaMapObjectId,
                placementMapObjectId: placementMapObjectId,
                displayName: trimmedName,
                taxonomyReferenceId: taxonomyReferenceId,
                varietyLabel: varietyLabel,
                acceptedIdentificationId: nil,
                acquisitionDate: acquisitionDate,
                acquisitionDateType: acquisitionDateType,
                groupingKind: groupingKind,
                quantity: quantity,
                // Matches `createPlant`'s own server-side defaults exactly
                // (`plants-inventory/domain/plant.ts`): every new plant
                // starts `lifecycleStage: 'planned'`, `status: 'active'`.
                lifecycleStage: .planned,
                status: .active,
                conditionNote: nil,
                careGuidanceNote: nil,
                revision: unconfirmedPlantRevision,
                createdByProfileId: profileId,
                createdAt: timestamp,
                updatedAt: timestamp
            )
            let operation = OutboxOperation(
                id: operationId,
                profileId: profileId,
                gardenId: gardenId,
                commandType: "plants.addPlant",
                commandVersion: PlantSyncCommandPayload.version,
                targetRecordIds: [plantId],
                expectedRevision: nil,
                payload: try PlantSyncCommandPayload.encode(
                    gardenId: gardenId,
                    command: .addPlant(
                        plantId: plantId,
                        request: AddPlantRequestPayload(
                            gardenAreaMapObjectId: gardenAreaMapObjectId,
                            placementMapObjectId: placementMapObjectId,
                            displayName: trimmedName,
                            taxonomyReferenceId: taxonomyReferenceId,
                            varietyLabel: varietyLabel,
                            acquisitionDate: acquisitionDate,
                            acquisitionDateType: acquisitionDateType,
                            groupingKind: groupingKind,
                            quantity: quantity
                        )
                    )
                ),
                createdAt: timestamp
            )
            return (projection, operation)
        }
    }
}

/// Still an online, gateway-backed read — see `AddPlant`'s doc comment for
/// the shared rationale. Now also writes through to `LocalPlantStore` after
/// every successful fetch (P5-IOS-02, Stage 4c): the four offline commands
/// below need a local row to load, validate against, and project forward,
/// and this is the only read path that can seed one for a plant this device
/// already knows about — mirrors `FeatureGardens.GetGarden`'s identical
/// `localStore.save(_:)` addition in Stage 4a.
public struct GetPlant: Sendable {
    private let gateway: any PlantGateway
    private let localStore: any LocalPlantStore

    public init(gateway: any PlantGateway, localStore: any LocalPlantStore) {
        self.gateway = gateway
        self.localStore = localStore
    }

    /// The immediately-available cached row, before any network call —
    /// mirrors `FeatureGardens.ListGardens.cached()`. Specifically what makes
    /// navigating straight from `PlantsHomeViewModel.performAdd()` to a
    /// plant's detail screen work while offline: `AddPlant` never reaches the
    /// server, so `callAsFunction`'s network fetch below would otherwise be
    /// the *only* way to view a plant this device just created, and it would
    /// fail every time for exactly that plant.
    public func cached(plantId: String) async throws -> Plant? {
        try await localStore.fetch(plantId: plantId)
    }

    public func callAsFunction(gardenId: String, plantId: String) async throws -> Plant {
        let plant = try await gateway.getPlant(gardenId: gardenId, plantId: plantId)
        try await localStore.save(plant)
        return plant
    }
}

/// Updates a plant's details as one local-only transaction: no network call.
/// See `AddPlant`'s doc comment for the shared rationale.
public struct UpdatePlantDetails: Sendable {
    private let localStore: any LocalPlantStore
    private let profileId: String
    private let now: @Sendable () -> Date
    private let generateOperationId: @Sendable () -> String

    public init(
        localStore: any LocalPlantStore,
        profileId: String,
        now: @escaping @Sendable () -> Date = Date.init,
        generateOperationId: @escaping @Sendable () -> String = UUIDv7.generate
    ) {
        self.localStore = localStore
        self.profileId = profileId
        self.now = now
        self.generateOperationId = generateOperationId
    }

    public func callAsFunction(
        gardenId: String,
        plantId: String,
        displayName: String? = nil,
        taxonomyReferenceId: FieldUpdate<String> = .unchanged,
        varietyLabel: FieldUpdate<String> = .unchanged,
        acquisitionDate: FieldUpdate<String> = .unchanged,
        acquisitionDateType: FieldUpdate<PlantAcquisitionDateType> = .unchanged,
        conditionNote: FieldUpdate<String> = .unchanged,
        careGuidanceNote: FieldUpdate<String> = .unchanged,
        quantity: FieldUpdate<Int> = .unchanged,
        expectedRevision: Int
    ) async throws -> Plant {
        let resolvedDisplayName = try displayName.map(validatedDisplayName)
        let timestamp = now()
        let operationId = generateOperationId()

        return try await localStore.commitOfflineMutation(plantId: plantId) { current in
            guard let current else {
                throw PlantCommandError.localRecordNotFound
            }

            let projection = Plant(
                id: current.id,
                gardenId: current.gardenId,
                gardenAreaMapObjectId: current.gardenAreaMapObjectId,
                placementMapObjectId: current.placementMapObjectId,
                displayName: resolvedDisplayName ?? current.displayName,
                taxonomyReferenceId: applying(taxonomyReferenceId, to: current.taxonomyReferenceId),
                varietyLabel: applying(varietyLabel, to: current.varietyLabel),
                acceptedIdentificationId: current.acceptedIdentificationId,
                acquisitionDate: applying(acquisitionDate, to: current.acquisitionDate),
                acquisitionDateType: applying(acquisitionDateType, to: current.acquisitionDateType),
                groupingKind: current.groupingKind,
                quantity: applying(quantity, to: current.quantity),
                lifecycleStage: current.lifecycleStage,
                status: current.status,
                conditionNote: applying(conditionNote, to: current.conditionNote),
                careGuidanceNote: applying(careGuidanceNote, to: current.careGuidanceNote),
                // Unchanged locally, matching `unconfirmedPlantRevision`'s own
                // reasoning below: the server, not this client, assigns the
                // next revision, which this device only learns once the push
                // that would consume this outbox operation is accepted.
                revision: current.revision,
                createdByProfileId: current.createdByProfileId,
                createdAt: current.createdAt,
                updatedAt: timestamp
            )
            let operation = OutboxOperation(
                id: operationId,
                profileId: profileId,
                gardenId: gardenId,
                commandType: "plants.updateDetails",
                commandVersion: PlantSyncCommandPayload.version,
                targetRecordIds: [plantId],
                expectedRevision: expectedRevision,
                payload: try PlantSyncCommandPayload.encode(
                    gardenId: gardenId,
                    command: .updateDetails(
                        plantId: plantId,
                        expectedRevision: expectedRevision,
                        request: UpdatePlantDetailsRequestPayload(
                            displayName: resolvedDisplayName,
                            taxonomyReferenceId: taxonomyReferenceId,
                            varietyLabel: varietyLabel,
                            acquisitionDate: acquisitionDate,
                            acquisitionDateType: acquisitionDateType,
                            conditionNote: conditionNote,
                            careGuidanceNote: careGuidanceNote,
                            quantity: quantity
                        )
                    )
                ),
                createdAt: timestamp
            )
            return (projection, operation)
        }
    }
}

/// Transitions a plant's lifecycle stage as one local-only transaction: no
/// network call. See `AddPlant`'s doc comment for the shared rationale. No
/// local validation of `stage` itself: any of the eight stages is reachable
/// from any other (`plants-inventory/domain/plant-lifecycle.ts`'s own
/// comment — "No hard state-machine ordering is enforced"), matching what
/// `PlantDetailView`'s picker already allows.
public struct TransitionPlantLifecycleStage: Sendable {
    private let localStore: any LocalPlantStore
    private let profileId: String
    private let now: @Sendable () -> Date
    private let generateOperationId: @Sendable () -> String

    public init(
        localStore: any LocalPlantStore,
        profileId: String,
        now: @escaping @Sendable () -> Date = Date.init,
        generateOperationId: @escaping @Sendable () -> String = UUIDv7.generate
    ) {
        self.localStore = localStore
        self.profileId = profileId
        self.now = now
        self.generateOperationId = generateOperationId
    }

    public func callAsFunction(
        gardenId: String,
        plantId: String,
        stage: PlantLifecycleStage,
        expectedRevision: Int
    ) async throws -> Plant {
        let timestamp = now()
        let operationId = generateOperationId()

        return try await localStore.commitOfflineMutation(plantId: plantId) { current in
            guard let current else {
                throw PlantCommandError.localRecordNotFound
            }

            let projection = Plant(
                id: current.id,
                gardenId: current.gardenId,
                gardenAreaMapObjectId: current.gardenAreaMapObjectId,
                placementMapObjectId: current.placementMapObjectId,
                displayName: current.displayName,
                taxonomyReferenceId: current.taxonomyReferenceId,
                varietyLabel: current.varietyLabel,
                acceptedIdentificationId: current.acceptedIdentificationId,
                acquisitionDate: current.acquisitionDate,
                acquisitionDateType: current.acquisitionDateType,
                groupingKind: current.groupingKind,
                quantity: current.quantity,
                lifecycleStage: stage,
                status: current.status,
                conditionNote: current.conditionNote,
                careGuidanceNote: current.careGuidanceNote,
                revision: current.revision,
                createdByProfileId: current.createdByProfileId,
                createdAt: current.createdAt,
                updatedAt: timestamp
            )
            let operation = OutboxOperation(
                id: operationId,
                profileId: profileId,
                gardenId: gardenId,
                commandType: "plants.transitionLifecycleStage",
                commandVersion: PlantSyncCommandPayload.version,
                targetRecordIds: [plantId],
                expectedRevision: expectedRevision,
                payload: try PlantSyncCommandPayload.encode(
                    gardenId: gardenId,
                    command: .transitionLifecycleStage(plantId: plantId, expectedRevision: expectedRevision, stage: stage)
                ),
                createdAt: timestamp
            )
            return (projection, operation)
        }
    }
}

/// Also how "delete a plant" works: there is no hard-delete endpoint, so the
/// detail screen's delete action calls this with `.removed`, not a
/// nonexistent `DELETE`. One local-only transaction: no network call. See
/// `AddPlant`'s doc comment for the shared rationale.
public struct SetPlantStatus: Sendable {
    private let localStore: any LocalPlantStore
    private let profileId: String
    private let now: @Sendable () -> Date
    private let generateOperationId: @Sendable () -> String

    public init(
        localStore: any LocalPlantStore,
        profileId: String,
        now: @escaping @Sendable () -> Date = Date.init,
        generateOperationId: @escaping @Sendable () -> String = UUIDv7.generate
    ) {
        self.localStore = localStore
        self.profileId = profileId
        self.now = now
        self.generateOperationId = generateOperationId
    }

    public func callAsFunction(
        gardenId: String,
        plantId: String,
        status: PlantStatus,
        expectedRevision: Int
    ) async throws -> Plant {
        let timestamp = now()
        let operationId = generateOperationId()

        return try await localStore.commitOfflineMutation(plantId: plantId) { current in
            guard let current else {
                throw PlantCommandError.localRecordNotFound
            }

            let projection = Plant(
                id: current.id,
                gardenId: current.gardenId,
                gardenAreaMapObjectId: current.gardenAreaMapObjectId,
                placementMapObjectId: current.placementMapObjectId,
                displayName: current.displayName,
                taxonomyReferenceId: current.taxonomyReferenceId,
                varietyLabel: current.varietyLabel,
                acceptedIdentificationId: current.acceptedIdentificationId,
                acquisitionDate: current.acquisitionDate,
                acquisitionDateType: current.acquisitionDateType,
                groupingKind: current.groupingKind,
                quantity: current.quantity,
                lifecycleStage: current.lifecycleStage,
                status: status,
                conditionNote: current.conditionNote,
                careGuidanceNote: current.careGuidanceNote,
                revision: current.revision,
                createdByProfileId: current.createdByProfileId,
                createdAt: current.createdAt,
                updatedAt: timestamp
            )
            let operation = OutboxOperation(
                id: operationId,
                profileId: profileId,
                gardenId: gardenId,
                commandType: "plants.setStatus",
                commandVersion: PlantSyncCommandPayload.version,
                targetRecordIds: [plantId],
                expectedRevision: expectedRevision,
                payload: try PlantSyncCommandPayload.encode(
                    gardenId: gardenId,
                    command: .setStatus(plantId: plantId, expectedRevision: expectedRevision, status: status)
                ),
                createdAt: timestamp
            )
            return (projection, operation)
        }
    }
}

/// Moves a plant's map placement as one local-only transaction: no network
/// call. See `AddPlant`'s doc comment for the shared rationale. `nil` for
/// either placement field clears it, matching `movePlant`'s own
/// online-gateway signature (plain optionals, not `FieldUpdate` — both
/// fields are always sent, never omitted, mirroring `normalizedPlacement`'s
/// server-side `input.field ?? null` handling).
public struct MovePlant: Sendable {
    private let localStore: any LocalPlantStore
    private let profileId: String
    private let now: @Sendable () -> Date
    private let generateOperationId: @Sendable () -> String

    public init(
        localStore: any LocalPlantStore,
        profileId: String,
        now: @escaping @Sendable () -> Date = Date.init,
        generateOperationId: @escaping @Sendable () -> String = UUIDv7.generate
    ) {
        self.localStore = localStore
        self.profileId = profileId
        self.now = now
        self.generateOperationId = generateOperationId
    }

    public func callAsFunction(
        gardenId: String,
        plantId: String,
        gardenAreaMapObjectId: String?,
        placementMapObjectId: String?,
        expectedRevision: Int
    ) async throws -> Plant {
        let timestamp = now()
        let operationId = generateOperationId()

        return try await localStore.commitOfflineMutation(plantId: plantId) { current in
            guard let current else {
                throw PlantCommandError.localRecordNotFound
            }

            let projection = Plant(
                id: current.id,
                gardenId: current.gardenId,
                gardenAreaMapObjectId: gardenAreaMapObjectId,
                placementMapObjectId: placementMapObjectId,
                displayName: current.displayName,
                taxonomyReferenceId: current.taxonomyReferenceId,
                varietyLabel: current.varietyLabel,
                acceptedIdentificationId: current.acceptedIdentificationId,
                acquisitionDate: current.acquisitionDate,
                acquisitionDateType: current.acquisitionDateType,
                groupingKind: current.groupingKind,
                quantity: current.quantity,
                lifecycleStage: current.lifecycleStage,
                status: current.status,
                conditionNote: current.conditionNote,
                careGuidanceNote: current.careGuidanceNote,
                revision: current.revision,
                createdByProfileId: current.createdByProfileId,
                createdAt: current.createdAt,
                updatedAt: timestamp
            )
            let operation = OutboxOperation(
                id: operationId,
                profileId: profileId,
                gardenId: gardenId,
                commandType: "plants.movePlant",
                commandVersion: PlantSyncCommandPayload.version,
                targetRecordIds: [plantId],
                expectedRevision: expectedRevision,
                payload: try PlantSyncCommandPayload.encode(
                    gardenId: gardenId,
                    command: .movePlant(
                        plantId: plantId,
                        expectedRevision: expectedRevision,
                        request: MovePlantRequestPayload(
                            gardenAreaMapObjectId: gardenAreaMapObjectId,
                            placementMapObjectId: placementMapObjectId
                        )
                    )
                ),
                createdAt: timestamp
            )
            return (projection, operation)
        }
    }
}

public struct SearchTaxonomyReferences: Sendable {
    private let gateway: any PlantGateway

    public init(gateway: any PlantGateway) {
        self.gateway = gateway
    }

    public func callAsFunction(gardenId: String, query: String? = nil, limit: Int? = nil) async throws -> [TaxonomyReference] {
        try await gateway.searchTaxonomyReferences(gardenId: gardenId, query: query, limit: limit)
    }
}

/// A plant created offline has no server-assigned revision yet. `0` is below
/// the contract's `Revision` minimum of `1`
/// (`packages/api-contracts/openapi.yaml`), so it can never be mistaken for a
/// real server revision — the exact sentinel and reasoning
/// `FeatureGardens.unconfirmedGardenRevision`/`FeatureMap`'s identical
/// `revision: 0` treatment already establish. `Plant.revision` stays a plain
/// `Int` for the same "not worth threading `Int?` through the whole feature
/// for this one local-only case" reasoning `unconfirmedGardenRevision`'s own
/// doc comment gives.
private let unconfirmedPlantRevision = 0

/// The contract's shared length rule for a plant's display name
/// (`packages/api-contracts/openapi.yaml`, `AddPlantRequest.displayName` /
/// `UpdatePlantDetailsRequest.displayName`, `minLength: 1, maxLength: 200`) —
/// also the backend's own `validateDisplayName`
/// (`plants-inventory/domain/plant.ts`). Not previously enforced client-side
/// (the "Add a plant" form's own `AddPlantFormValidation` only checked
/// non-empty); step 2 of the local mutation transaction (architecture/
/// offline-synchronization.md, section "6") is where the upper bound belongs
/// now that an offline command has nowhere else to be checked before it is
/// queued — the same "previously-unenforced contract limit, wired in now"
/// pattern `FeatureGardens.gardenNameMaxLength`'s own doc comment describes.
private let plantDisplayNameMaxLength = 200

private func validatedDisplayName(_ displayName: String) throws -> String {
    let trimmed = displayName.trimmingCharacters(in: .whitespacesAndNewlines)

    guard !trimmed.isEmpty, trimmed.count <= plantDisplayNameMaxLength else {
        throw PlantCommandError.invalidDisplayName
    }

    return trimmed
}

/// Applies a `FieldUpdate` to a current optional value: `.unchanged` keeps
/// `current`, `.set(value)` (including `.set(nil)`, which clears it) becomes
/// the new value — mirrors the backend's own `changes.field !== undefined ?
/// ... : plant.field` handling in `updatePlantDetails`
/// (`plants-inventory/domain/plant.ts`).
private func applying<Value>(_ update: FieldUpdate<Value>, to current: Value?) -> Value? {
    switch update {
    case .unchanged: current
    case let .set(value): value
    }
}
