// swift-tools-version: 6.2

import PackageDescription

// The Apple client lives in the monorepo but deliberately stays outside the
// pnpm workspace, so Swift Package Manager — not an .xcodeproj — is the unit of
// truth for module boundaries. Targets are the mechanism that enforces the
// dependency rule: a Core target cannot name a Feature target, so the compiler
// rejects an inverted import instead of a reviewer having to notice it.
//
// Phase 2 adds project.yml/Verdery.xcodeproj (generated by xcodegen, never
// edited directly) alongside this file: Firebase Authentication needs
// entitlements, a custom Info.plist, and a bundled GoogleService-Info.plist
// that a bare SPM executable cannot express. The Xcode project is a thin
// deployment shell with no sources of its own beyond the app entry point
// already defined here — this file remains the source of truth for every
// module boundary.
//
// Source: architecture/README.md, section "5. Repository Shape";
// architecture/ios-application-design.md, sections "4. Application Structure"
// and "21. Dependency Rules".
let package = Package(
    name: "Verdery",
    // English is the development language; every other catalogue is a
    // translation of it.
    defaultLocalization: "en",
    // iOS 18.0 is the pinned deployment target. macOS is declared only so the
    // package builds and tests headlessly with `swift build` and `swift test`
    // on a developer machine and in CI; no macOS product is shipped.
    //
    // Source: ADR-0009, "Apple deployment target".
    platforms: [.iOS(.v18), .macOS(.v15)],
    products: [
        .library(name: "CoreDomain", targets: ["CoreDomain"]),
        .library(name: "CoreNetworking", targets: ["CoreNetworking"]),
        .library(name: "CoreObservability", targets: ["CoreObservability"]),
        .library(name: "CoreLocalization", targets: ["CoreLocalization"]),
        .library(name: "CoreAuthentication", targets: ["CoreAuthentication"]),
        .library(name: "CorePersistence", targets: ["CorePersistence"]),
        .library(name: "CoreSynchronization", targets: ["CoreSynchronization"]),
        .library(name: "FeatureHealth", targets: ["FeatureHealth"]),
        .library(name: "FeatureAuthentication", targets: ["FeatureAuthentication"]),
        .library(name: "FeatureGardens", targets: ["FeatureGardens"]),
        .library(name: "FeatureMap", targets: ["FeatureMap"]),
        .library(name: "FeaturePlants", targets: ["FeaturePlants"]),
        .library(name: "FeatureObservations", targets: ["FeatureObservations"]),
        .library(name: "FeatureTasks", targets: ["FeatureTasks"]),
        .library(name: "AppComposition", targets: ["AppComposition"]),
    ],
    dependencies: [
        // Sign in with Apple, Google, and email magic link, per
        // architecture/identity-and-authorization.md, section "3. Initial
        // Sign-In Methods"; App Check token generation, per section
        // "12. App Check". Only the FirebaseAuth and FirebaseAppCheck
        // products are linked; nothing in this package touches Analytics,
        // Crashlytics, or any other Firebase product.
        .package(url: "https://github.com/firebase/firebase-ios-sdk", from: "12.16.0"),
        // The per-profile local read model store, per
        // architecture/ios-application-design.md, section "6. Persistence"
        // and implementation-plan.md work package P2-IOS-01.
        .package(url: "https://github.com/groue/GRDB.swift", from: "7.11.1"),
    ],
    targets: [
        // Core: platform-neutral meaning. Depends on nothing, so geometry
        // semantics stay testable without a network, a database, or SwiftUI.
        .target(name: "CoreDomain"),

        .target(
            name: "CoreObservability",
            dependencies: ["CoreDomain"]
        ),

        // Localized strings are a Core capability rather than a feature asset
        // because validation issue codes produced by CoreDomain must resolve to
        // the same text on every screen that surfaces them.
        .target(
            name: "CoreLocalization",
            dependencies: ["CoreDomain"],
            resources: [.process("Resources")]
        ),

        .target(
            name: "CoreNetworking",
            dependencies: ["CoreDomain", "CoreObservability"]
        ),

        // The only target that imports FirebaseAuth and FirebaseAppCheck.
        // Exposes `AuthTokenProvider` and `AppCheckTokenProvider` (both
        // declared in CoreDomain) so CoreNetworking depends on those
        // protocols, never on this target or on Firebase directly.
        //
        // Source: architecture/ios-application-design.md, section
        // "21. Dependency Rules" ("Firebase ... types remain inside adapters
        // or feature infrastructure").
        .target(
            name: "CoreAuthentication",
            dependencies: [
                "CoreDomain",
                "CoreObservability",
                .product(name: "FirebaseAuth", package: "firebase-ios-sdk"),
                .product(name: "FirebaseAppCheck", package: "firebase-ios-sdk"),
            ]
        ),

        // The local GRDB/SQLite database: opening and migrating the one
        // per-profile database file, and a repository-style store per local
        // table. The only target besides `FeatureGardens` that imports GRDB
        // — every table's repository protocol returns plain CoreDomain
        // types, never a GRDB row, per architecture/ios-application-
        // design.md, section "21. Dependency Rules" ("GRDB ... types remain
        // inside adapters or feature infrastructure").
        //
        // Source: architecture/ios-application-design.md, sections
        // "4. Application Structure" and "7. Local Persistence";
        // architecture/offline-synchronization.md, section "5. Local
        // Tables"; implementation-plan.md work package P5-IOS-01.
        .target(
            name: "CorePersistence",
            dependencies: [
                "CoreDomain",
                .product(name: "GRDB", package: "GRDB.swift"),
            ]
        ),

        // The synchronization seam: `SyncEngine`, the protocol a future
        // push/pull engine implements, plus a local-storage-only
        // implementation. No network dependency yet — see `SyncEngine.swift`
        // for why `CoreNetworking` is deliberately not a dependency here
        // until a later work package builds the real push/pull protocol.
        //
        // Source: architecture/ios-application-design.md, section
        // "8. Synchronization Integration"; architecture/offline-
        // synchronization.md; implementation-plan.md work package
        // P5-IOS-01.
        .target(
            name: "CoreSynchronization",
            dependencies: ["CoreDomain", "CorePersistence"]
        ),

        // Feature template. A feature may depend on Core; Core never names a
        // feature.
        .target(
            name: "FeatureHealth",
            dependencies: ["CoreDomain", "CoreNetworking", "CoreLocalization"]
        ),

        .target(
            name: "FeatureAuthentication",
            dependencies: ["CoreDomain", "CoreAuthentication", "CoreNetworking", "CoreLocalization"]
        ),

        .target(
            name: "FeatureGardens",
            dependencies: [
                "CoreDomain",
                "CoreNetworking",
                "CoreLocalization",
                // For `CorePersistence.LocalDatabase`, which opens and
                // migrates the database `GRDBGardenStore` reads and writes.
                // `FeatureGardens` still depends on GRDB directly too: its
                // own read-model repository (`GRDBGardenStore`,
                // `GardenRecord`) uses the GRDB API directly, the same way
                // it always has — `CorePersistence` centralizes the
                // database's lifecycle and schema, not every table's
                // repository.
                "CorePersistence",
                .product(name: "GRDB", package: "GRDB.swift"),
            ]
        ),

        // The map editor: SwiftUI Canvas rendering, selection, gestures,
        // commands, properties, measurement overlays, and an optional MapKit
        // backdrop.
        //
        // Gained a GRDB dependency in P5-IOS-02 (Stage 4b): `LocalMapStore`
        // durably persists the local `garden_object` read model an offline
        // command's optimistic projection commits against, the same way
        // `FeatureGardens`'s `GRDBGardenStore` already does for `garden` —
        // see that target's own comment just above for why `CorePersistence`
        // centralizes the database's lifecycle/schema while the feature owns
        // its own read-model repository directly against GRDB.
        //
        // Source: implementation-plan.md work packages P3-IOS-01, P3-IOS-02,
        // P5-IOS-02.
        .target(
            name: "FeatureMap",
            dependencies: [
                "CoreDomain",
                "CoreNetworking",
                "CoreLocalization",
                "CorePersistence",
                .product(name: "GRDB", package: "GRDB.swift"),
            ]
        ),

        // Plant inventory, observations/history, and manual tasks (Phase 4).
        // `FeatureObservations`/`FeatureTasks` still have no GRDB dependency
        // — see each one's own view model doc comment
        // (`ObservationsTimelineViewModel`, `TasksListViewModel`) for the
        // always-fresh-from-server reasoning, the same choice `FeatureMap`
        // already made and for closely related reasons: every mutating
        // command on an observation or a task carries a server-checked
        // `expectedRevision` (where one applies), so a locally cached,
        // possibly-stale revision would turn every command into a coin flip
        // on a `409`/`412` instead of the deliberate check the backend
        // performs. `FeaturePlants` gained a GRDB dependency in P5-IOS-02
        // (Stage 4c): `LocalPlantStore` durably persists the local `plant`
        // read model an offline command's optimistic projection commits
        // against, the same way `FeatureMap`'s `GRDBMapStore` already does
        // for `garden_object` (Stage 4b) — see that target's own comment
        // above for why `CorePersistence` centralizes the database's
        // lifecycle/schema while the feature owns its own read-model
        // repository directly against GRDB. `PlantDetailViewModel`'s reads
        // stay always-fresh-from-server for the same reason as before; only
        // the five offline-capable commands route through this new table.
        //
        // Source: implementation-plan.md work packages P4-IOS-01, P5-IOS-02.
        .target(
            name: "FeaturePlants",
            dependencies: [
                "CoreDomain",
                "CoreNetworking",
                "CoreLocalization",
                "CorePersistence",
                .product(name: "GRDB", package: "GRDB.swift"),
            ]
        ),

        .target(
            name: "FeatureObservations",
            dependencies: ["CoreDomain", "CoreNetworking", "CoreLocalization"]
        ),

        .target(
            name: "FeatureTasks",
            dependencies: ["CoreDomain", "CoreNetworking", "CoreLocalization"]
        ),

        // The single composition root that constructs adapters and injects them
        // through explicit initializers.
        .target(
            name: "AppComposition",
            dependencies: [
                "CoreDomain",
                "CoreNetworking",
                "CoreObservability",
                "CoreLocalization",
                "CoreAuthentication",
                // For `LocalDatabase.open`, which the garden store's
                // composition still opens directly here — see
                // `AppCompositionRoot.localGardenStore()`.
                "CorePersistence",
                "FeatureHealth",
                "FeatureAuthentication",
                "FeatureGardens",
                "FeatureMap",
                "FeaturePlants",
                "FeatureObservations",
                "FeatureTasks",
                .product(name: "FirebaseCore", package: "firebase-ios-sdk"),
            ]
        ),

        .executableTarget(
            name: "VerderyApp",
            dependencies: ["AppComposition"]
        ),

        .testTarget(
            name: "CoreDomainTests",
            dependencies: ["CoreDomain"]
        ),
        .testTarget(
            name: "CoreNetworkingTests",
            dependencies: ["CoreNetworking"]
        ),
        .testTarget(
            name: "CoreLocalizationTests",
            dependencies: ["CoreLocalization"]
        ),
        .testTarget(
            name: "CorePersistenceTests",
            dependencies: ["CorePersistence"]
        ),
        .testTarget(
            name: "CoreSynchronizationTests",
            dependencies: ["CoreSynchronization"]
        ),
        .testTarget(
            name: "FeatureHealthTests",
            dependencies: ["FeatureHealth"]
        ),
        .testTarget(
            name: "FeatureGardensTests",
            dependencies: [
                "FeatureGardens",
                // For the offline-mutation tests (P5-IOS-02): they construct
                // a real GRDB database via `CorePersistence.LocalDatabase
                // .migrator` and read the resulting `sync_outbox` rows back
                // through `CorePersistence.GRDBSyncOutboxStore`, the same
                // real-database-over-mock approach
                // `CorePersistenceTests.MigrationIntegrityTests` already
                // uses for schema/transaction tests.
                "CorePersistence",
                .product(name: "GRDB", package: "GRDB.swift"),
            ]
        ),
        .testTarget(
            name: "FeatureMapTests",
            dependencies: [
                "FeatureMap",
                // For the offline-mutation tests (P5-IOS-02): a real GRDB
                // database via `CorePersistence.LocalDatabase.migrator`,
                // matching `FeatureGardensTests`'s identical rationale above.
                "CorePersistence",
                .product(name: "GRDB", package: "GRDB.swift"),
            ]
        ),
        .testTarget(
            name: "FeaturePlantsTests",
            dependencies: [
                "FeaturePlants",
                // For the offline-mutation tests (P5-IOS-02): a real GRDB
                // database via `CorePersistence.LocalDatabase.migrator`,
                // matching `FeatureGardensTests`/`FeatureMapTests`'s
                // identical rationale.
                "CorePersistence",
                .product(name: "GRDB", package: "GRDB.swift"),
            ]
        ),
        .testTarget(
            name: "FeatureObservationsTests",
            dependencies: ["FeatureObservations"]
        ),
        .testTarget(
            name: "FeatureTasksTests",
            dependencies: ["FeatureTasks"]
        ),
        .testTarget(
            name: "ArchitectureTests"
        ),
    ]
)
