// swift-tools-version: 6.2

import PackageDescription

// The Apple client lives in the monorepo but deliberately stays outside the
// pnpm workspace, so Swift Package Manager — not an .xcodeproj — is the unit of
// truth for module boundaries. Targets are the mechanism that enforces the
// dependency rule: a Core target cannot name a Feature target, so the compiler
// rejects an inverted import instead of a reviewer having to notice it.
//
// Phase 2 adds project.yml/Verdery.xcodeproj (generated by xcodegen, never
// edited directly) alongside this file: Firebase Authentication needs
// entitlements, a custom Info.plist, and a bundled GoogleService-Info.plist
// that a bare SPM executable cannot express. The Xcode project is a thin
// deployment shell with no sources of its own beyond the app entry point
// already defined here — this file remains the source of truth for every
// module boundary.
//
// Source: architecture/README.md, section "5. Repository Shape";
// architecture/ios-application-design.md, sections "4. Application Structure"
// and "21. Dependency Rules".
let package = Package(
    name: "Verdery",
    // English is the development language; every other catalogue is a
    // translation of it.
    defaultLocalization: "en",
    // iOS 18.0 is the pinned deployment target. macOS is declared only so the
    // package builds and tests headlessly with `swift build` and `swift test`
    // on a developer machine and in CI; no macOS product is shipped.
    //
    // Source: ADR-0009, "Apple deployment target".
    platforms: [.iOS(.v18), .macOS(.v15)],
    products: [
        .library(name: "CoreDomain", targets: ["CoreDomain"]),
        .library(name: "CoreNetworking", targets: ["CoreNetworking"]),
        .library(name: "CoreObservability", targets: ["CoreObservability"]),
        .library(name: "CoreLocalization", targets: ["CoreLocalization"]),
        .library(name: "CoreAuthentication", targets: ["CoreAuthentication"]),
        .library(name: "FeatureHealth", targets: ["FeatureHealth"]),
        .library(name: "FeatureAuthentication", targets: ["FeatureAuthentication"]),
        .library(name: "FeatureGardens", targets: ["FeatureGardens"]),
        .library(name: "FeatureMap", targets: ["FeatureMap"]),
        .library(name: "AppComposition", targets: ["AppComposition"]),
    ],
    dependencies: [
        // Sign in with Apple, Google, and email magic link, per
        // architecture/identity-and-authorization.md, section "3. Initial
        // Sign-In Methods"; App Check token generation, per section
        // "12. App Check". Only the FirebaseAuth and FirebaseAppCheck
        // products are linked; nothing in this package touches Analytics,
        // Crashlytics, or any other Firebase product.
        .package(url: "https://github.com/firebase/firebase-ios-sdk", from: "12.16.0"),
        // The per-profile local read model store, per
        // architecture/ios-application-design.md, section "6. Persistence"
        // and implementation-plan.md work package P2-IOS-01.
        .package(url: "https://github.com/groue/GRDB.swift", from: "7.11.1"),
    ],
    targets: [
        // Core: platform-neutral meaning. Depends on nothing, so geometry
        // semantics stay testable without a network, a database, or SwiftUI.
        .target(name: "CoreDomain"),

        .target(
            name: "CoreObservability",
            dependencies: ["CoreDomain"]
        ),

        // Localized strings are a Core capability rather than a feature asset
        // because validation issue codes produced by CoreDomain must resolve to
        // the same text on every screen that surfaces them.
        .target(
            name: "CoreLocalization",
            dependencies: ["CoreDomain"],
            resources: [.process("Resources")]
        ),

        .target(
            name: "CoreNetworking",
            dependencies: ["CoreDomain", "CoreObservability"]
        ),

        // The only target that imports FirebaseAuth and FirebaseAppCheck.
        // Exposes `AuthTokenProvider` and `AppCheckTokenProvider` (both
        // declared in CoreDomain) so CoreNetworking depends on those
        // protocols, never on this target or on Firebase directly.
        //
        // Source: architecture/ios-application-design.md, section
        // "21. Dependency Rules" ("Firebase ... types remain inside adapters
        // or feature infrastructure").
        .target(
            name: "CoreAuthentication",
            dependencies: [
                "CoreDomain",
                "CoreObservability",
                .product(name: "FirebaseAuth", package: "firebase-ios-sdk"),
                .product(name: "FirebaseAppCheck", package: "firebase-ios-sdk"),
            ]
        ),

        // Feature template. A feature may depend on Core; Core never names a
        // feature.
        .target(
            name: "FeatureHealth",
            dependencies: ["CoreDomain", "CoreNetworking", "CoreLocalization"]
        ),

        .target(
            name: "FeatureAuthentication",
            dependencies: ["CoreDomain", "CoreAuthentication", "CoreNetworking", "CoreLocalization"]
        ),

        .target(
            name: "FeatureGardens",
            dependencies: [
                "CoreDomain",
                "CoreNetworking",
                "CoreLocalization",
                .product(name: "GRDB", package: "GRDB.swift"),
            ]
        ),

        // The map editor: SwiftUI Canvas rendering, selection, gestures,
        // commands, properties, measurement overlays, and an optional MapKit
        // backdrop. No GRDB dependency — see `MapEditorViewModel`'s doc
        // comment for the always-fresh-from-server caching decision.
        //
        // Source: implementation-plan.md work packages P3-IOS-01, P3-IOS-02.
        .target(
            name: "FeatureMap",
            dependencies: ["CoreDomain", "CoreNetworking", "CoreLocalization"]
        ),

        // The single composition root that constructs adapters and injects them
        // through explicit initializers.
        .target(
            name: "AppComposition",
            dependencies: [
                "CoreDomain",
                "CoreNetworking",
                "CoreObservability",
                "CoreLocalization",
                "CoreAuthentication",
                "FeatureHealth",
                "FeatureAuthentication",
                "FeatureGardens",
                "FeatureMap",
                .product(name: "FirebaseCore", package: "firebase-ios-sdk"),
            ]
        ),

        .executableTarget(
            name: "VerderyApp",
            dependencies: ["AppComposition"]
        ),

        .testTarget(
            name: "CoreDomainTests",
            dependencies: ["CoreDomain"]
        ),
        .testTarget(
            name: "CoreNetworkingTests",
            dependencies: ["CoreNetworking"]
        ),
        .testTarget(
            name: "CoreLocalizationTests",
            dependencies: ["CoreLocalization"]
        ),
        .testTarget(
            name: "FeatureHealthTests",
            dependencies: ["FeatureHealth"]
        ),
        .testTarget(
            name: "FeatureGardensTests",
            dependencies: ["FeatureGardens"]
        ),
        .testTarget(
            name: "FeatureMapTests",
            dependencies: ["FeatureMap"]
        ),
        .testTarget(
            name: "ArchitectureTests"
        ),
    ]
)
