import type { Uuid } from '../../../shared/identifiers/uuid.js';
import type { SuitabilityAssessmentResult } from '../domain/suitability-finding.js';

export interface CandidateSuitabilityAssessmentRepository {
  /** `id` is generated by the caller (`generateUuidV7()`), not this repository — the pure engine stays id-free, the same "the use case assigns ids at persistence time" convention `RuleEvidenceSpec` documents for the recommendation engine. */
  insert(id: Uuid, assessment: SuitabilityAssessmentResult): Promise<void>;
  /** The most recently computed assessment for a candidate, or `null` if none has ever been run. */
  findLatest(candidateId: Uuid): Promise<SuitabilityAssessmentResult | null>;
}
