/// Keys the visual plant journal resolves against the localization catalogue
/// (P11-MEDIA-01): the shot-purpose vocabulary a photograph is labelled with
/// when it is attached, and the control that asks for it.
///
/// A separate enum for the same structural reason every other key set here
/// gives: an enum's cases cannot be declared in an extension, and
/// `LocalizationKey.swift` is already at this repository's 600-line ceiling.
public enum ObservationJournalLocalizationKey: String, Sendable, CaseIterable {
    case observationsJournalTitle = "observations.journal.title"
    case observationsJournalPurposeFilterLabel = "observations.journal.purposeFilterLabel"
    case observationsJournalAllPurposes = "observations.journal.allPurposes"
    case observationsJournalEmpty = "observations.journal.empty"
    case observationsJournalEmptyForPurpose = "observations.journal.emptyForPurpose"
    case observationsJournalOpenButton = "observations.journal.openButton"
    case observationsSymptomsReported = "observations.symptoms.reported"
    case observationsSymptomsLegend = "observations.symptoms.legend"
    case observationsSymptomKindLabel = "observations.symptoms.kindLabel"
    case observationsSymptomSeverityLabel = "observations.symptoms.severityLabel"
    case observationsSymptomAdd = "observations.symptoms.add"
    case observationsSymptomRemove = "observations.symptoms.remove"
    case observationsSymptomLeafSpots = "observations.symptom.leafSpots"
    case observationsSymptomLeafYellowing = "observations.symptom.leafYellowing"
    case observationsSymptomLeafCurling = "observations.symptom.leafCurling"
    case observationsSymptomWilting = "observations.symptom.wilting"
    case observationsSymptomHolesOrChewing = "observations.symptom.holesOrChewing"
    case observationsSymptomMouldOrMildew = "observations.symptom.mouldOrMildew"
    case observationsSymptomDieback = "observations.symptom.dieback"
    case observationsSymptomStuntedGrowth = "observations.symptom.stuntedGrowth"
    case observationsSymptomUnusualGrowth = "observations.symptom.unusualGrowth"
    case observationsSeverityMild = "observations.severity.mild"
    case observationsSeverityModerate = "observations.severity.moderate"
    case observationsSeveritySevere = "observations.severity.severe"
    case observationsMeasurementsLegend = "observations.measurements.legend"
    case observationsMeasurementKindLabel = "observations.measurements.kindLabel"
    case observationsMeasurementValueLabel = "observations.measurements.valueLabel"
    case observationsMeasurementUnitLabel = "observations.measurements.unitLabel"
    case observationsMeasurementUnitPlaceholder = "observations.measurements.unitPlaceholder"
    case observationsMeasurementAdd = "observations.measurements.add"
    case observationsMeasurementRemove = "observations.measurements.remove"
    case observationsMeasurementKindHeight = "observations.measurementKind.height"
    case observationsMeasurementKindWidth = "observations.measurementKind.width"
    case observationsMeasurementKindCount = "observations.measurementKind.count"
    case observationsPhotoPurposeLabel = "observations.photoPurpose.label"
    case observationsPhotoPurposeWholePlant = "observations.photoPurpose.wholePlant"
    case observationsPhotoPurposeLeafFront = "observations.photoPurpose.leafFront"
    case observationsPhotoPurposeLeafBack = "observations.photoPurpose.leafBack"
    case observationsPhotoPurposeStemOrBark = "observations.photoPurpose.stemOrBark"
    case observationsPhotoPurposeFlower = "observations.photoPurpose.flower"
    case observationsPhotoPurposeFruit = "observations.photoPurpose.fruit"
    case observationsPhotoPurposeSymptomCloseUp = "observations.photoPurpose.symptomCloseUp"
    case observationsPhotoPurposeContextOrFreeForm = "observations.photoPurpose.contextOrFreeForm"
}
