import type { Uuid } from '../../../shared/identifiers/uuid.js';
import type { PublicationMediaRole } from './client-update-item-repository.js';

export interface PublicationWorkLogItemInput {
  readonly id: Uuid;
  readonly occurredAt: Date;
  readonly description: string;
  readonly sourceWorkLogId: Uuid | null;
}

export interface PublicationMediaItemInput {
  readonly id: Uuid;
  readonly occurredAt: Date;
  readonly mediaRecordId: Uuid;
  readonly mediaRole: PublicationMediaRole;
  readonly caption: string | null;
}

export interface PublicationGardenSnapshotItemInput {
  readonly id: Uuid;
  readonly occurredAt: Date;
  readonly overviewText: string;
  readonly snapshotData: unknown;
}

export interface PublicationTimelineEntryItemInput {
  readonly id: Uuid;
  readonly occurredAt: Date;
  readonly entryText: string;
}

export interface PublicationObservationItemInput {
  readonly id: Uuid;
  readonly occurredAt: Date;
  readonly narrativeText: string;
  readonly sourceObservationId: Uuid | null;
}

export interface PublicationStaffAttributionInput {
  readonly id: Uuid;
  readonly staffProfileId: Uuid;
  readonly displayName: string;
  readonly roleLabel: string | null;
}

/**
 * Steps 3 and 4 of the six-step publish transaction (collaboration-and-
 * client-sharing.md section 10), as one call: "Creates an immutable
 * publication version and item snapshots" plus "Creates explicit media-
 * entitlement records" — one row per `mediaItems` entry, engagement-scoped,
 * exactly as `media_entitlement`'s own `(engagement_id, media_record_id)`
 * shape requires. All ids are pre-generated by the caller (`PublishClientUpdate`),
 * matching every other insert-input shape in this module.
 */
export interface CreatePublicationVersionInput {
  readonly id: Uuid;
  readonly clientUpdateId: Uuid;
  readonly engagementId: Uuid;
  readonly gardenId: Uuid;
  readonly title: string;
  readonly summary: string;
  readonly clientUpdateRevisionAtPublish: number;
  readonly publishedAt: Date;
  readonly publishedByProfileId: Uuid;
  readonly workLogItems: readonly PublicationWorkLogItemInput[];
  readonly mediaItems: readonly PublicationMediaItemInput[];
  readonly gardenSnapshotItem: PublicationGardenSnapshotItemInput | null;
  readonly timelineEntryItems: readonly PublicationTimelineEntryItemInput[];
  readonly observationItems: readonly PublicationObservationItemInput[];
  readonly staffAttributions: readonly PublicationStaffAttributionInput[];
}

export type PublicationItemDetail =
  | {
      readonly id: Uuid;
      readonly kind: 'work_log';
      readonly occurredAt: Date;
      readonly description: string;
      readonly sourceWorkLogId: Uuid | null;
    }
  | {
      readonly id: Uuid;
      readonly kind: 'media';
      readonly occurredAt: Date;
      readonly mediaRecordId: Uuid;
      readonly mediaRole: PublicationMediaRole;
      readonly caption: string | null;
    }
  | {
      readonly id: Uuid;
      readonly kind: 'garden_snapshot';
      readonly occurredAt: Date;
      readonly overviewText: string;
      readonly snapshotData: unknown;
    }
  | {
      readonly id: Uuid;
      readonly kind: 'timeline_entry';
      readonly occurredAt: Date;
      readonly entryText: string;
    }
  | {
      readonly id: Uuid;
      readonly kind: 'observation';
      readonly occurredAt: Date;
      readonly narrativeText: string;
      readonly sourceObservationId: Uuid | null;
    };

export interface PublicationStaffAttributionDetail {
  readonly id: Uuid;
  readonly staffProfileId: Uuid;
  readonly displayName: string;
  readonly roleLabel: string | null;
  readonly createdAt: Date;
}

/** Mirrors `collaboration.publication_version` plus its read-back items and staff attributions — the full shape `PublishClientUpdate` returns. */
export interface PublicationVersionDetail {
  readonly id: Uuid;
  readonly clientUpdateId: Uuid;
  readonly engagementId: Uuid;
  readonly gardenId: Uuid;
  readonly versionNumber: number;
  readonly title: string;
  readonly summary: string;
  readonly clientUpdateRevisionAtPublish: number;
  readonly publishedAt: Date;
  readonly publishedByProfileId: Uuid;
  readonly createdAt: Date;
  readonly items: readonly PublicationItemDetail[];
  readonly staffAttributions: readonly PublicationStaffAttributionDetail[];
}

export interface PublicationRepository {
  /**
   * Performs steps 3 and 4 of the six-step publish transaction. Throws a
   * unique-violation on `publication_version_client_update_id_key` if a
   * version already exists for this `clientUpdateId` — a defense-in-depth
   * backstop the revision guard already makes unreachable through this
   * command's own ordinary call path; see `PublishClientUpdate`'s own
   * pre-check-plus-catch handling for how this is translated into a clean
   * `409`, never a raw constraint violation.
   */
  create(input: CreatePublicationVersionInput): Promise<PublicationVersionDetail>;
}
